src/person.js, src/resumes/left-right.vue, src/resumes/material-dark.vue, src/resumes/oblique.vue, src/resumes/side-bar.vue, src/resumes/template.vue
Something else.
Some people have middle name and it's be nice to have its own place in the person object imho.
---
Hi, 
I hope you'll accept this change. 
Cheers,
G.
=> Add middle name attribute to the person object

config/index.js
A bug fix for #41 which caused images and fonts not loading on local dev server.
Images and fonts are not loaded on the local dev server.
=> Fix assets path for dev-server #41

DEVELOPER.md, src/lang/de.js, src/lang/en.js, src/person.js, src/resumes/left-right.vue, src/resumes/material-dark.vue, src/resumes/oblique.vue, src/resumes/resumes.js, src/resumes/side-bar.vue, src/resumes/template.vue, src/terms.js
Language support as discussed in #32 
There is no language support (see #32)
If something should be done another way, I can fix it.
I can also add a section in the `DEVELOPER.md` how to add a new language, but I want to wait what the final way of defining languages will be.
=> Add language support

src/lang/pt.js, src/person.js, src/terms.js
Portuguese lang file & relevant imports
¯\_(ツ)_/¯
=> ADDED support for portuguese lang

src/lang/it.js, src/person.js, src/terms.js
=> Added Italian localisation

src/lang/cn.js, src/person.js, src/terms.js
Chinese language files and configuration
No problem without this PR.
=> Added Chinese language support.

src/lang/it.js
An updated version of Italian translation file, added the missing `About me` string.
=> Updated the italian translation

src/lang/pt.js
Portuguese lang translation update
---
=> updated portuguese lang translation

src/lang/es.js, src/person.js, src/terms.js
=> Add spanish language file

src/lang/cn.js, src/lang/fr.js
Chinese translation for 'about me' and improved French translations.
=> Add CN translation / improve FR translation

src/lang/th.js, src/person.js, src/terms.js
=> Add Thai language file.

src/lang/ru.js, src/person.js, src/terms.js
=> Add Russian language files

src/lang/sv.js, src/person.js, src/terms.js
=> Added Swedish translation

src/lang/id.js, src/person.js, src/terms.js
Added indonesian languange files
=> Added indonesian language files

src/resumes/material-dark.vue
- Fixed typo in CSS
- Minor typo causing linting issues / style being ignored
=> fix(material-dark-template): Fixed css

src/lang/hu.js, src/person.js, src/terms.js
=> Add Hungarian language files

src/lang/pl.js, src/person.js, src/terms.js
=> Add Polish language file

README.md
- A TYPO-FIX
Just the tiniest of typos, missing word, but it was bugging me.  Hope you don't mind.
=> Update README.md for a typo/missing word.

src/lang/ja.js, src/person.js, src/terms.js
=> Add Japanese language

src/lang/nl.js, src/person.js, src/terms.js
=> Add Dutch (nl) Language

src/resumes/left-right.vue, src/resumes/material-dark.vue, src/resumes/oblique.vue, src/resumes/purple.vue, src/resumes/side-bar.vue
changing github and website info to be optional
some people don't have website or github
=> make github and website info optional

src/lang/lt.js, src/person.js, src/terms.js
- A NEW FEATURE
Lithuanian language support.
=> ADD Lithuanian language support

src/lang/tr.js
=> ADD Turkish language support

resume/data.yml, src/lang/ca.js, src/terms.js
-Something else (new language)
-Added catalan language
=> feat: catalan language added

resume/data.yml, src/lang/el.js, src/terms.js
New language support
Added Greek Language support
=> added greek language support

src/resumes/material-dark.vue
=> fix error with HTML tags

index.html
=> Index mobile update

resume/data.yml, src/lang/ka.js
=> Add Georgian (ka) language

src/lang/fr.js
- Add fr locales.
No problem, just add some fr locales.
=> Add some locales for fr language

src/lang/cn.js
"捐款" Should be "贡献", former is meaning to give someone money
=> fixed misuse of translation in chinese

README.md
=> Add License

src/lang/de.js
Some of the German strings where wrong, this includes a correction
The names of some sections are wrong in German
IMPORTANT: READ THIS BEFORE SUBMISSION:
=> fix german strings

README.md
=> added the clone instruction to the readme

src/resumes/cool.vue, src/resumes/creative.vue, src/resumes/left-right-rtl.vue, src/resumes/left-right.vue, src/resumes/material-dark.vue, src/resumes/oblique.vue, src/resumes/options.js, src/resumes/purple.vue, src/resumes/side-bar-rtl.vue, src/resumes/side-bar.vue
Updated links to all social contacts in the resume. Refactored all the hardcoded contact links using computed property, which will generate `contactLinks` object having all contact links and will be easier to use while developing a new template.
=> Update contact links in resume

README.md
- IMPROVED DOCS
- Need to run `npm install` from the correct directory
=> Update README, add change directory step.

src/lang/ru.js
- A BUGFIX
https://github.com/salomonelli/best-resume-ever/issues/336
=> added born to ru lang

src/resumes/cool.vue, src/resumes/material-dark.vue
- A BUGFIX
https://github.com/salomonelli/best-resume-ever/issues/338
I add v-if to the birth section if birth doesn't exist in data.yml.
It looks like this:
=> hide birth section if birth doesn't exists

README.md
link for cloning this repo was not working without ".git" part
Link for cloning was not working with out ".git" part
=> added .git to link

README.md
1. Clone this repository.
```
git clone https://github.com/salomonelli/best-resume-ever
changed to 
git clone https://github.com/salomonelli/best-resume-ever.git
=> Added .git extension

resume/data.yml, src/lang/nb-no.js, src/terms.js
The problem was that it was not norwegian language support before :)
=> Adds norwegian language support

src/lang/no-nn.js, src/terms.js
Translation into Norwegian Nynorsk
I couldn't get my CV in my native language.
=> Translation into Norwegian Nynorsk

src/lang/fr.js
- A typo fix
There is a spelling mistake
=> spelling mistake

src/lang/es.js
=> Variables 'born' and 'bornIn' were added in spanish language

src/resumes/material-dark.vue
- An enhancement to the material-dark template 
Added hyperlinks for education and experience sections in material-dark
=> Added hyperlinks to material-dark sections

src/resumes/cool.vue
- A BUGFIX
Before cursor;
After the fix;
=> Fixed cursor setting to pointer when a component's website is undefined for cool template

src/resumes/material-dark.vue
A typo fix.
Changed margin-botton to margin-bottom in the material-dark template.
=> .description selector class typo

README.md, resume/data.yml
Improved documentation around the building process, and an option for using the computer's file managing system.  Additionally, documentation within data.yml on which sections are not used in all resume templates and instruction to delete any leftover John Doe information.
User may be confused by the messages in the terminal when npm installing. Users may not know how to navigate to files/edit files within their terminal and give up on using the tool.  Users may spend pointless time filling out the hobbies section and then not having it on their resume. Users may end up with a resume that still has some of John Doe's information on it.
<!--
=> Documentation work margaret w

src/lang/es.js
- A typo fix
There is a typo in Spanish language.
=> Fix typo in es.js
